# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
books = Book.create([{author_last:"Pratchett", author_first:"Terry", pages:210, title:"The Color of Magic", finish_date:"1/1/1901"},
                     {author_last:"Gould", author_first:"Stephen", pages:323, title:"The Panda's Thumb", finish_date:"1/1/1901"},
                     {author_last:"Calvino", author_first:"Italo", pages:124, title:"Six Memos for the Next Millenium", finish_date:"1/1/1901"},
                     {author_last:"White", author_first:"T. H.", pages:288, title:"The Sword in the Stone", finish_date:"1/1/1901"},
                     {author_last:"Sardar", author_first:"Ziauddin", pages:171, title:"Introducing Chaos", finish_date:"1/1/1901"},
                     {author_last:"Anderson", author_first:"Poul", pages:164, title:"Three Hearts and Three Lions", finish_date:"1/1/1901"},
                     {author_last:"McCarthy", author_first:"Cormac", pages:246, title:"The Orchard Keeper", finish_date:"1/1/1901"},
                     {author_last:"Calvino", author_first:"Italo", pages:260, title:"If on a winter's night a traveler", finish_date:"1/1/1901"},
                     {author_last:"Lewis", author_first:"Sinclair", pages:325, title:"Babbitt", finish_date:"1/1/1901"},
                     {author_last:"Sprague de Camp", author_first:"L.", pages:191, title:"Conan the Buccaneer", finish_date:"1/1/1901"},
                     {author_last:"Sprague de Camp", author_first:"L.", pages:274, title:"Lest Darkness Fall", finish_date:"1/1/1901"},
                     {author_last:"Ellison", author_first:"Harlan", pages:158, title:"All the Sounds of the Fear", finish_date:"1/1/1901"},
                     {author_last:"Zelazny", author_first:"Roger", pages:142, title:"Jack of Shadows", finish_date:"1/1/1901"},
                     {author_last:"LeGuin", author_first:"Ursula", pages:179, title:"The Eye of the Heron", finish_date:"1/1/1901"},
                     {author_last:"Alexander", author_first:"Lloyd", pages:185, title:"Westmark", finish_date:"1/1/1901"},
                     {author_last:"Howard", author_first:"Robert", pages:224, title:"Conan the Adventurer", finish_date:"1/1/1901"},
                     {author_last:"Howard", author_first:"Robert", pages:194, title:"The Lost Valley of Iskander", finish_date:"1/1/1901"},
                     {author_last:"Moorcock", author_first:"Michael", pages:160, title:"The Sailor on the Seas of Fate", finish_date:"1/1/1901"},
                     {author_last:"Carver", author_first:"Terrell", pages:78, title:"Engels", finish_date:"1/1/1901"},
                     {author_last:"Carver", author_first:"Raymond", pages:159, title:"What We Talk About When We Talk About Love", finish_date:"1/1/1901"},
                     {author_last:"Gibson", author_first:"William", pages:204, title:"Burning Chrome", finish_date:"1/1/1901"},
                     {author_last:"Joyce", author_first:"James", pages:160, title:"Dubliners", finish_date:"1/1/1901"},
                     {author_last:"Ozick", author_first:"Cynthia", pages:179, title:"Dictation", finish_date:"1/1/1901"},
                     {author_last:"Mantel", author_first:"Hilary", pages:181, title:"Fludd", finish_date:"1/1/1901"},
                     {author_last:"St. John Mandel", author_first:"Emily", pages:230, title:"Last Night in Montreal", finish_date:"1/1/1901"},
                     {author_last:"Trotsky", author_first:"Leon", pages:256, title:"Literature and Revolution", finish_date:"1/1/1901"},
                     {author_last:"Einstein", author_first:"Albert", pages:120, title:"Essays In Humanism", finish_date:"1/1/1901"},
                     {author_last:"Clark", author_first:"Paul", pages:159, title:"The Miner's Fight for Democracy", finish_date:"1/1/1901"},
                     {author_last:"Albert", author_first:"David", pages:197, title:"Quantum Mechanics and Experience", finish_date:"1/1/1901"},
                     {author_last:"Heinlein", author_first:"Robert", pages:255, title:"The Moon is a Harsh Mistress", finish_date:"1/1/1901"},
                     {author_last:"Gould", author_first:"Stephen", pages:450, title:"The Flamingo's Smile", finish_date:"1/1/1901"},
                     {author_last:"Betancourt", author_first:"John", pages:438, title:"Weird Tales: Seven Decades of Terror", finish_date:"1/1/1901"},
                     {author_last:"Fante", author_first:"John", pages:266, title:"The Wine of Youth", finish_date:"1/1/1901"},
                     {author_last:"Howard", author_first:"Robert", pages:366, title:"The Second Book of Robert E. Howard", finish_date:"1/1/1901"},
                     {author_last:"Dick", author_first:"Philip", pages:397, title:"Paycheck", finish_date:"1/1/1901"},
                     {author_last:"LeGuin", author_first:"Ursula", pages:236, title:"Buffalo Gals", finish_date:"1/1/1901"},
                     {author_last:"Meiksins Wood", author_first:"Ellen", pages:198, title:"The Origins of Capitalism: A Longer View", finish_date:"1/1/1901"},
                     {author_last:"McElroy", author_first:"Clint", pages:238, title:"The Adventure Zone", finish_date:"1/1/1901"},
                     {author_last:"Wolfe", author_first:"Gene", pages:409, title:"Shadow & Claw", finish_date:"1/1/1901"},
                     {author_last:"Matthiesen", author_first:"Peter", pages:892, title:"Shadow Country", finish_date:"1/1/1901"},
                     {author_last:"McCarthy", author_first:"Cormac", pages:471, title:"Suttree", finish_date:"1/1/1901"},
                     {author_last:"Catton", author_first:"Eleanor", pages:830, title:"The Luminaries", finish_date:"1/1/1901"},
                     {author_last:"Shaara", author_first:"Michael", pages:345, title:"Killer Angels", finish_date:"1/1/1901"},
                     {author_last:"Di Lampedusa", author_first:"Giuseppe", pages:320, title:"The Leopard", finish_date:"1/1/1901"},
                     {author_last:"Garcia Marquez", author_first:"Gabriel", pages:348, title:"Love in the Time of Cholera", finish_date:"1/1/1901"},
                     {author_last:"Jordan", author_first:"Robert", pages:509, title:"The Further Chronicles of Conan", finish_date:"1/1/1901"},
                     {author_last:"Borges", author_first:"Jorge Luis", pages:515, title:"Collected Fictions", finish_date:"1/1/1901"},
                     {author_last:"Gould", author_first:"Stephen", pages:510, title:"Bully for Brontosaurus", finish_date:"1/1/1901"},
                     {author_last:"Manguel", author_first:"Alberto", pages:949, title:"Black Water", finish_date:"1/1/1901"},
                     {author_last:"Pratchett", author_first:"Terry", pages:241, title:"The Light Fantastic", finish_date:"1/1/1901"},
                     {author_last:"Graves", author_first:"Robert", pages:347, title:"Good-bye to All That", finish_date:"1/1/1901"},
                     {author_last:"Howard", author_first:"Robert", pages:207, title:"Kull", finish_date:"1/1/1901"},
                     {author_last:"Sprague de Camp", author_first:"L.", pages:260, title:"The Goblin Tower", finish_date:"1/1/1901"},
                     {author_last:"Bailey", author_first:"Robin", pages:244, title:"Swords Against the Shadowland", finish_date:"1/1/1901"},
                     {author_last:"Abbott", author_first:"Edwin", pages:228, title:"The Annotated Flatland", finish_date:"1/1/1901"},
                     {author_last:"LeGuin", author_first:"Ursula", pages:311, title:"The Dispossessed", finish_date:"1/1/1901"},
                     {author_last:"Crossley-Holland", author_first:"Kevin", pages:350, title:"The Seeing Stone", finish_date:"1/1/1901"},
                     {author_last:"McKinley", author_first:"Robin", pages:272, title:"The Blue Sword", finish_date:"1/1/1901"},
                     {author_last:"LeGuin", author_first:"Ursula", pages:323, title:"The Left Hand of Darkness", finish_date:"1/1/1901"},
                     {author_last:"Cooper", author_first:"Susan", pages:244, title:"The Dark is Rising", finish_date:"1/1/1901"},
                     {author_last:"Gould", author_first:"Stephen", pages:230, title:"Full House", finish_date:"1/1/1901"},
                     {author_last:"Darwin", author_first:"Charles", pages:145, title:"The Autobiography of Charles Darwin", finish_date:"1/1/1901"},
                     {author_last:"Caesar", author_first:"Julius", pages:222, title:"The Gallic War", finish_date:"1/1/1901"},
                     {author_last:"Cook", author_first:"Glen", pages:240, title:"A Shadow of All Night Falling", finish_date:"1/1/1901"},
                     {author_last:"Watt-Evans", author_first:"Lawrence", pages:268, title:"The Sword of Bheleu", finish_date:"1/1/1901"},
                     {author_last:"Ende", author_first:"Michael", pages:445, title:"The Neverending Story", finish_date:"1/1/1901"},
                     {author_last:"Levi", author_first:"Carlo", pages:268, title:"Christ Stopped at Eboli", finish_date:"1/1/1901"},
                     {author_last:"Leguin", author_first:"Ursula", pages:544, title:"Always Coming Home", finish_date:"1/1/1901"},
                     {author_last:"Stanley Robinson", author_first:"Kim", pages:572, title:"Red Mars", finish_date:"1/1/1901"},
                     {author_last:"Liu", author_first:"Cixin", pages:396, title:"The Three-Body Problem", finish_date:"1/1/1901"},
                     {author_last:"Modesitt, Jr.", author_first:"L. E.", pages:501, title:"The Magic of Recluse", finish_date:"1/1/1901"},
                     {author_last:"Isenberg", author_first:"Nancy", pages:321, title:"White Trash", finish_date:"1/1/1901"},
                     {author_last:"Tacitus", author_first:"Cornelius", pages:367, title:"The Annals of Rome", finish_date:"1/1/1901"},
                     {author_last:"Ryan", author_first:"Cornelius", pages:595, title:"A Bridge Too Far", finish_date:"1/1/1901"},
                     {author_last:"Salway", author_first:"Peter", pages:739, title:"Roman Britain", finish_date:"1/1/1901"},
                     {author_last:"Solzhenitsyn", author_first:"Aleksandr", pages:536, title:"Cancer Ward", finish_date:"1/1/1901"},
                     {author_last:"Zimmerman Bradley", author_first:"Marion", pages:876, title:"The Mists of Avalon", finish_date:"1/1/1901"},
                     {author_last:"Abercrombie", author_first:"Joe", pages:451, title:"Red Country", finish_date:"1/1/1901"},
                     {author_last:"Cook", author_first:"Glen", pages:427, title:"The Tyranny of the Night", finish_date:"1/1/1901"},
                     {author_last:"Cook", author_first:"Glen", pages:375, title:"The Tower of Fear", finish_date:"1/1/1901"},
                     {author_last:"Cook", author_first:"Glen", pages:213, title:"Reap the East Wind", finish_date:"1/1/1901"},
                     {author_last:"Cook", author_first:"Glen", pages:323, title:"All Darkness Met", finish_date:"1/1/1901"},
                     {author_last:"Cook", author_first:"Glen", pages:248, title:"Octobers Baby", finish_date:"1/1/1901"},
                     {author_last:"Steinbeck", author_first:"John", pages:174, title:"Tortilla Flat", finish_date:"1/1/1901"},
                     {author_last:"Roth", author_first:"Henry", pages:285, title:"Mercy of a Rude Stream", finish_date:"1/1/1901"},
                     {author_last:"Kafka", author_first:"Franz", pages:218, title:"Amerika", finish_date:"1/1/1901"},
                     {author_last:"Joyce", author_first:"James", pages:783, title:"Ulysses", finish_date:"1/1/1901"},
                     {author_last:"OConnor", author_first:"Flannery", pages:243, title:"The Violent Bear it Away", finish_date:"1/1/1901"},
                     {author_last:"McCarthy", author_first:"Cormac", pages:302, title:"All the Pretty Horses", finish_date:"1/1/1901"},
                     {author_last:"McCarthy", author_first:"Cormac", pages:426, title:"The Crossing", finish_date:"1/1/1901"},
                     {author_last:"McCarthy", author_first:"Cormac", pages:292, title:"Cities of the Plain", finish_date:"1/1/1901"},
                    ])